In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r'preprocessing_ofCIC-IDS2017.csv')

In [3]:
df.shape

(2520798, 42)

In [4]:
df.columns

Index(['Unnamed: 0', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', 'Bwd Packet Length Max', 'Flow Bytes/s',
       ' Flow Packets/s', 'Fwd IAT Total', 'Bwd IAT Total', 'Fwd PSH Flags',
       ' Fwd URG Flags', ' Fwd Header Length', ' Bwd Header Length',
       'Fwd Packets/s', ' Bwd Packets/s', ' Min Packet Length',
       ' Max Packet Length', 'FIN Flag Count', ' SYN Flag Count',
       ' RST Flag Count', ' PSH Flag Count', ' ACK Flag Count',
       ' URG Flag Count', ' CWE Flag Count', ' ECE Flag Count',
       ' Down/Up Ratio', ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', 'Idle Mean', ' Label'],
      dtype='object')

In [5]:
df[' Label'].value_counts()

 Label
BENIGN                        2095057
DoS Hulk                       172846
DDoS                           128014
PortScan                        90694
DoS GoldenEye                   10286
FTP-Patator                      5931
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
Bot                              1948
Web Attack � Brute Force         1470
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [7]:
df.head()

,Unnamed: 0,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Bwd Packet Length Max,Flow Bytes/s,Flow Packets/s,Fwd IAT Total,...,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Idle Mean,Label
0,0,3,2,0,12,0,0,4.000000e+06,666666.66670,3,...,12,0,0,33,-1,1,20,0.0,0.0,BENIGN
1,1,109,1,1,6,6,6,1.100917e+05,18348.62385,0,...,6,1,6,29,256,0,20,0.0,0.0,BENIGN
2,2,52,1,1,6,6,6,2.307692e+05,38461.53846,0,...,6,1,6,29,256,0,20,0.0,0.0,BENIGN
3,3,34,1,1,6,6,6,3.529412e+05,58823.52941,0,...,6,1,6,31,329,0,20,0.0,0.0,BENIGN
4,4,3,2,0,12,0,0,4.000000e+06,666666.66670,3,...,12,0,0,32,-1,1,20,0.0,0.0,BENIGN

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
LE=LabelEncoder()

In [10]:
df[' Label']=LE.fit_transform(df[' Label'])

In [11]:
df.sample()

,Unnamed: 0,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Bwd Packet Length Max,Flow Bytes/s,Flow Packets/s,Fwd IAT Total,...,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Idle Mean,Label
2337899,2337899,126456,8,4,548,2942,1476,27598.5323,94.894667,126456,...,548,4,2942,8192,110,7,20,0.0,0.0,0

In [12]:
X=df.drop(' Label',axis=1)
y=df[' Label']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42,stratify=y)

In [14]:
ss=StandardScaler()

In [15]:
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [17]:
LR=LogisticRegression()
DTC=DecisionTreeClassifier()
RFC=RandomForestClassifier()
KNN=KNeighborsClassifier()

### Logistic Regrssion

In [18]:
LR.fit(x_train,y_train)

C:\Users\kusha\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [19]:
y_pred=LR.predict(x_test)

In [20]:
from sklearn.metrics import recall_score,classification_report,confusion_matrix,f1_score

In [21]:
print('recall:',recall_score(y_test,y_pred,average='micro'))

recall: 0.9833333333333333

In [22]:
print(classification_report(y_test,y_pred))

C:\Users\kusha\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99    628518
           1       0.55      0.01      0.02       584
           2       0.98      1.00      0.99     38404
           3       0.92      0.86      0.89      3086
           4       0.97      0.94      0.96     51854
           5       0.81      0.73      0.77      1568
           6       0.92      0.54      0.68      1616
           7       0.00      0.00      0.00      1779
           8       0.08      0.33      0.13         3
           9       0.50      0.09      0.15        11
          10       0.96      0.99      0.98     27208
          11       0.00      0.00      0.00       966
          12       0.00      0.00      0.00       441
          13       0.00      0.00      0.00         6
          14       0.00      0.00      0.00       196

    accuracy                           0.98    756240
   macro avg       0.51      0.43      0.44    756240
weighted avg       0.98      0.98      0.98    756240

C:\Users\kusha\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kusha\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [23]:
LR.score(x_test,y_test)

0.9833333333333333

### Decision tree

In [24]:
DTC.fit(x_train,y_train)

DecisionTreeClassifier()

In [25]:
DTC_pred=DTC.predict(x_test)

In [26]:
print('Classification Report:','\n',classification_report(y_test,DTC_pred))
print('Recall:',recall_score(y_test,DTC_pred,average='weighted'))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    628518
           1       0.98      0.98      0.98       584
           2       1.00      1.00      1.00     38404
           3       1.00      1.00      1.00      3086
           4       1.00      1.00      1.00     51854
           5       1.00      1.00      1.00      1568
           6       1.00      0.99      0.99      1616
           7       1.00      1.00      1.00      1779
           8       1.00      1.00      1.00         3
           9       0.47      0.82      0.60        11
          10       1.00      1.00      1.00     27208
          11       0.99      1.00      0.99       966
          12       0.94      0.97      0.95       441
          13       1.00      0.83      0.91         6
          14       0.90      0.95      0.92       196

    accuracy                           1.00    756240
   macro avg       0.95      0.97      0.96    756240
weighted avg       1.00      1.00      1.00    756240

Recall: 0.9997143763884481

### RandomForest

In [33]:
RFC.fit(x_train,y_train)

RandomForestClassifier()

In [34]:
RFC_pred=RFC.predict(x_test)

In [35]:
print('Classification Report:','\n',classification_report(y_test,RFC_pred))
print('Recall:',recall_score(y_test,RFC_pred,average='weighted'))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    628518
           1       1.00      0.96      0.98       584
           2       1.00      1.00      1.00     38404
           3       1.00      1.00      1.00      3086
           4       1.00      1.00      1.00     51854
           5       1.00      1.00      1.00      1568
           6       1.00      0.99      1.00      1616
           7       1.00      1.00      1.00      1779
           8       1.00      0.67      0.80         3
           9       1.00      0.91      0.95        11
          10       1.00      1.00      1.00     27208
          11       1.00      0.99      1.00       966
          12       0.93      0.98      0.95       441
          13       1.00      0.17      0.29         6
          14       0.97      0.89      0.93       196

    accuracy                           1.00    756240
   macro avg       0.99      0.90      0.93    756240
weighted avg       1.00      1.00      1.00    756240

Recall: 0.9997990056066857

### KNN

In [36]:
KNN.fit(x_train,y_train)

KNeighborsClassifier()

In [37]:
KNN_pred=KNN.predict(x_test)

In [38]:
print('Classification Report:','\n',classification_report(y_test,KNN_pred))
print('Recall:',recall_score(y_test,KNN_pred,average='weighted'))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    628518
           1       0.85      0.86      0.86       584
           2       1.00      1.00      1.00     38404
           3       0.99      0.99      0.99      3086
           4       1.00      1.00      1.00     51854
           5       0.99      0.99      0.99      1568
           6       0.99      0.98      0.99      1616
           7       1.00      0.99      1.00      1779
           8       1.00      0.67      0.80         3
           9       0.20      0.09      0.13        11
          10       1.00      1.00      1.00     27208
          11       0.99      0.97      0.98       966
          12       0.91      0.94      0.93       441
          13       1.00      0.17      0.29         6
          14       0.94      0.98      0.96       196

    accuracy                           1.00    756240
   macro avg       0.92      0.84      0.86    756240
weighted avg       1.00      1.00      1.00    756240

Recall: 0.9991325505130646